yaml file update

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -93,3 +93,13 @@ jobs:
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4
+      - name: Start Server
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            yarn run dev
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            npm run dev
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
